theme = "onedark"

[editor]
line-number = "relative"
cursorline = true
bufferline = "always"
auto-pairs = false
auto-format = false

[editor.cursor-shape]
insert = "bar"
normal = "underline"
select = "block"

[editor.lsp]
auto-signature-help = false

[editor.indent-guides]
render = true

[keys.normal]
# Regular Keys
p = "paste_clipboard_before"
y = "yank_main_selection_to_clipboard"
f = "file_picker_in_current_directory"
esc = ["collapse_selection", "keep_primary_selection"]
tab = ["goto_next_paragraph", "collapse_selection"]
# Shift Keys
D = ["ensure_selections_forward", "extend_to_line_end"]
X = "extend_line_above"
G = "goto_file_end"
S-tab = ["goto_prev_paragraph", "collapse_selection"]
# Control Keys
C-left = "goto_previous_buffer"
C-right = "goto_next_buffer"
C-x = ":bc!"
C-s = ":w"
# Other Keys
[keys.normal.g]
a = "code_action"
g = [":new", ":insert-output lazygit", ":bc", ":redraw"]
     
[keys.insert]
C-s = [":w", "normal_mode"]
C-left = "goto_previous_buffer"
C-right = "goto_next_buffer"

[editor.soft-wrap]
enable = true
