#! /bin/sh

# Fix Issues With Java Applications
export _JAVA_AWT_WM_NONREPARENTING=1
wmname LG3D

# Setup Laptop Display
xrandr --output eDP --mode 1920x1080 --rate 60 --rotate normal

# Set Desktop Background
feh --bg-fill ~/MEGA/Wallpapers/wall3.png &

# AUTOSTART BASIC PROGRAMS
sxhkd &              # Hotkeys
volumeicon &         # Volume Tray Icon
lxqt-powermanagement &  # Power Tray Icon
polybar &          # System Bar
nm-applet &          # Internet

# BSPWM CONFIGURATIONS
bspc config border_width         2
bspc config window_gap           8
bspc config top_padding          30
bspc config normal_border_color "#5E81AC"
bspc config focused_border_color "#FF9100"
bspc config presel_feedback_color "#FF9100"

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true

# Set Workspaces
bspc monitor -d 1 2 3 4 5 6 7 8 9

# Set Default Mouse Cursor
xsetroot -cursor_name left_ptr &
